apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  ## IAM Role *name* (not ARN). After `terraform apply`: copy from
  ## `terraform output -json karpenter | jq -r .value.node_role_name`
  role: k8s-emad-temp-replace-from-terraform-output
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: k8s-Emad-128768042813-dev-eks
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: k8s-Emad-128768042813-dev-eks
